apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-backend-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casino-backend
  template:
    metadata:
      labels:
        app: casino-backend
    spec:
      containers:
      - name: casino-backend
        image: 673037114724.dkr.ecr.us-east-1.amazonaws.com/casino-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: casino-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: casino-backend-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 67
