apiVersion: v1
kind: Service
metadata:
  name: casino-backend-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
spec:
  type: LoadBalancer
  selector:
    app: casino-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000